ALTER TABLE `bds_live`.`tpl_shadow_supplier` 
ADD COLUMN `COMPANY_STRAPLINE_TEXT` TEXT NULL DEFAULT NULL  AFTER `PHYSICAL_ADDRESS_POST_CODE` , 
ADD COLUMN `COMPANY_ABOUTUS_TEXT` TEXT NULL DEFAULT NULL  AFTER `COMPANY_STRAPLINE_TEXT` ,
CHANGE COLUMN `COMPANY_PROFILE_TEXT` `COMPANY_PROFILE_TEXT` TEXT NULL DEFAULT NULL  AFTER `COMPANY_STRAPLINE_TEXT` ;

ALTER TABLE `bds_live`.`tpl_shadow_supplier` 
ADD COLUMN `COMPANY_STRAPLINE_TEXT` TEXT NULL DEFAULT NULL  AFTER `PHYSICAL_ADDRESS_POST_CODE` , 
ADD COLUMN `COMPANY_ABOUTUS_TEXT` TEXT NULL DEFAULT NULL  AFTER `COMPANY_STRAPLINE_TEXT` ,
CHANGE COLUMN `COMPANY_PROFILE_TEXT` `COMPANY_PROFILE_TEXT` TEXT NULL DEFAULT NULL  AFTER `COMPANY_STRAPLINE_TEXT` ;