ALTER TABLE `bds_live`.`tpl_supplier_media` ADD COLUMN `IS_FEATURED` TINYINT(1) NOT NULL  AFTER `IS_EMBED_SOURCE` , 
ADD COLUMN `PRINT_ORDER` INT(11) NOT NULL  AFTER `IS_HIGH_RESO` , 
CHANGE COLUMN `REC_DATETIME` `REC_DATETIME` DATETIME NOT NULL  AFTER `REC_ID` , 
CHANGE COLUMN `CLIENT_REC_ID` `CLIENT_REC_ID` INT(11) NOT NULL  AFTER `REC_DATETIME` , 
CHANGE COLUMN `SUPPLIER_REC_ID` `SUPPLIER_REC_ID` INT(11) NOT NULL  AFTER `CLIENT_REC_ID` , 
CHANGE COLUMN `NAME` `NAME` VARCHAR(50) NOT NULL  AFTER `SUPPLIER_REC_ID` , 
CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL  AFTER `NAME` , 
CHANGE COLUMN `MEDIA_FILE_SIZE` `MEDIA_FILE_SIZE` INT(11) NOT NULL  AFTER `MEDIA_TYPE_REC_ID` , 
CHANGE COLUMN `MEDIA_EMBED_SOURCE` `MEDIA_EMBED_SOURCE` VARCHAR(2560) CHARACTER SET 'latin1' NOT NULL  AFTER `MEDIA_FILE_SIZE` ;