ALTER TABLE `bds_live`.`tpl_directory_offering` CHARACTER SET = utf8 , COLLATE = utf8_unicode_ci , 
ADD COLUMN `TENANT_REC_ID` INT(11) NULL  FIRST , 
ADD COLUMN `DIRECTORY_PERIOD_REC_ID` INT(11) NOT NULL  AFTER `REC_TIMESTAMP` ;

