delimiter $$
    CREATE TABLE `tpl_shadow_supplier_directory` (
    `REC_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `REC_DATETIME` datetime NOT NULL,
    `REC_TIMESTAMP` datetime NOT NULL,
    `SHADOW_SUPPLIER_REC_ID` int(11) unsigned NOT NULL,
    `DIRECTORY_REC_ID` int(11) unsigned NOT NULL,
    `DIRECTORY_PERIOD_REC_ID` varchar(4) CHARACTER SET latin1 DEFAULT NULL,
    `SHADOW_ROOT_REC_ID` int(11) unsigned DEFAULT NULL,
    PRIMARY KEY (`REC_ID`),
    KEY `SHADOW_SUPPLIER_REC_ID` (`SHADOW_SUPPLIER_REC_ID`),
    KEY `DIRECTORY_REC_ID` (`DIRECTORY_REC_ID`),
    CONSTRAINT `TPL_SHADOW_SUPPLIER_DIRECTORY_fk` FOREIGN KEY (`SHADOW_SUPPLIER_REC_ID`) REFERENCES `tpl_shadow_supplier` (`REC_ID`) ON UPDATE CASCADE,
    CONSTRAINT `TPL_SHADOW_SUPPLIER_DIRECTORY_fk1` FOREIGN KEY (`DIRECTORY_REC_ID`) REFERENCES `tpl_directory` (`REC_ID`) ON UPDATE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8
$$

