ALTER TABLE `db_live`.`tpl_directory_period`
ADD COLUMN `DIRECTORY_PERIOD_NAME` VARCHAR(100) NOT NULL AFTER `DIRECTORY_YEAR`,
ADD COLUMN `DIRECTORY_PERIOD_CODE` VARCHAR(25) DEFAULT NULL AFTER `DIRECTORY_YEAR`; 