ALTER TABLE `db_live`.`tpl_supplier_category_product` 
CHANGE COLUMN `LABEL_NAME` `PRODUCT_TITLE` VARCHAR(255) NOT NULL DEFAULT ''  , 
CHANGE COLUMN `VARIETAL` `PRODUCT_DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL  , 
CHANGE COLUMN `VINTAGE` `PRODUCT_VALUE_PRICE` FLOAT(9,2) NULL DEFAULT NULL  , 
CHANGE COLUMN `REGION_OF_ORIGIN` `PRODUCT_OFFER_PRICE` FLOAT(9,2) NULL DEFAULT NULL  , 
CHANGE COLUMN `COUNTRY_OF_ORIGIN` `PRODUCT_CHECKOUT_URL` VARCHAR(255) NULL DEFAULT NULL  ;




