CREATE TABLE `tpl_category_summary` (
 `REC_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
 `REC_DATETIME` datetime NOT NULL,
 `REC_TIMESTAMP` datetime NOT NULL,
 `NODE_ID` varchar(15) DEFAULT NULL,
 `PARENT_PRODUCT_CATEGORY_REC_ID` varchar(15) DEFAULT NULL,
 `NAME` varchar(255) NOT NULL DEFAULT '',
 `IS_FINAL_LEAF` varchar(15) DEFAULT NULL,
 `NUMBER_OF_SUPPLIERS` int(11) unsigned DEFAULT NULL,
 `IMAGEURl` varchar(255) NOT NULL DEFAULT '',
 PRIMARY KEY (`REC_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;