<?php

//class datagrid {
//
//    private $grid = null;
//    private $grid_name = null;
//    public $grid_width = '100%';
//    public $allowsorting = true;
//
//    public function __construct($grid_name) {
//        // constructor
//        
//        error_log("__construct datagrid");
//        $this->init($grid_name);
//    }
//
//    public function __destruct() {
//        // destructor
//        error_log("__destruct");
//    }
//
//    public function init($grid_name) {
//
//        $path_doc_root = $_SERVER["DOCUMENT_ROOT"];
//        require_once( $path_doc_root . "/include/KoolPHPSuite/KoolGrid/koolgrid.php");
//        require_once ( $path_doc_root . "/include/KoolPHPSuite/KoolAjax/koolajax.php");
//        $this->grid = new KoolGrid($grid_name);
//        $this->grid->scriptFolder = "./../include/KoolPHPSuite/KoolGrid";
//        $this->grid->styleFolder = "default";
//        $this->grid->MasterTable->Pager = new GridPrevNextAndNumericPager();
//        $this->grid->MasterTable->ShowFunctionPanel = true;
//        $this->grid->AjaxEnabled = true;
//        $this->grid->Width = $this->grid_width;
//        $this->grid->AllowSorting = true;
//        $this->grid->AllowSelecting = true;
//        $this->grid->RowAlternative = true;
//        $this->grid->SingleColumnSorting = true;
//        $this->grid->ShowStatus = true;
//        //$this->grid->ShowFooter = true;
//        $this->grid->ClientSettings->ClientEvents["OnRowSelect"] = "Handle_OnRowSelect";
//        $this->grid->ClientSettings->ClientEvents["OnRowClick"] = "Handle_OnRowClick";
//        $this->grid->ClientSettings->ClientEvents["OnRowDoubleClick"] = "Handle_OnRowDoubleClick";
//    }
//
//    public function process() {
//        $this->grid->Process();
//    }
//
//    public function render() {
//        //echo $koolajax->Render();
//        echo $this->grid->Render();
//    }
//
//    public function columnAlias($column_name, $alias) {
//        $col = new gridboundcolumn();
//        $col->DataField = $column_name;
//        $col->HeaderText = $alias;
//        $this->grid->MasterTable->AddColumn($col);
//    }
//
//    public function columnDateTime($column_name, $alias) {
//        $col = new griddatetimecolumn();
//        $col->DataField = $column_name;
//        $col->HeaderText = $alias;
//        $col->FormatString = 'jS F Y';
//        $this->grid->MasterTable->AddColumn($col);
//    }
//
//    public function columnCustom($column_name, $column_template) {
//        $col = new GridCustomColumn();
//        $col->ItemTemplate = $column_template;
//        $col->HeaderText = $column_name;
//        $this->grid->MasterTable->AddColumn($col);
//    }
//
//    public function columnsToDisable($column_names) {
//        $this->grid->MasterTable->DisableAutoGenerateDataFields = '"' . $column_names . '"';
//    }
//
//    public function autoGenerateColumns() {
//        $this->grid->MasterTable->AutoGenerateColumns = true;
//    }
//
//    public function columnHide($column_name) {
//        $col = new gridboundcolumn();
//        $col->DataField = $column_name;
//        $col->Visible = false;
//        $this->grid->MasterTable->AddColumn($col);
//    }
//
//    public function columnAddEdit($alias) {
//        $col = new GridEditDeleteColumn();
//        $col->HeaderText = ($alias);
//        $col->Align = "center";
//        $this->grid->MasterTable->EditSettings->Mode = "Inline";
//        $this->grid->MasterTable->AddColumn($col);
//    }
//
//    public function activateAdvancedGrid() {
//        $this->grid->AllowFiltering = true;
//        $this->grid->AllowInserting = $this->allowsorting;
//        $this->grid->MasterTable->ShowFunctionPanel = true;
//    }
//
//    public function datasource($query) {
//        global $DB_NAME;
//        require '../config.php';
//        $db_con = mysql_connect($DB_HOST, $DB_USER, $DB_PASS);
//        mysql_select_db($DB_NAME, $db_con);
//        $ds = new MySQLDataSource($db_con);
//        $ds->SelectCommand = $query;
//        $this->grid->DataSource = $ds;
//    }
//
//// export functions 
//    public function exportPdf() {
//        ob_end_clean();
//        $this->grid->ExportSettings->FileName = $this->grid_name;
//        $this->grid->ExportSettings->IgnorePaging = true;
//        $this->grid->GetInstanceMasterTable()->ExportToPDF();
//    }
//
//    public function exportXls($file_name) {
//        ob_end_clean();
//        $this->ExportSettings->FileName = $this->grid_name;
//        $this->grid->ExportSettings->IgnorePaging = true;
//        $this->grid->GetInstanceMasterTable()->ExportToExcel();
//    }
//
//    public function exportCsv($file_name) {
//        ob_end_clean();
//        $this->ExportSettings->FileName = $this->grid_name;
//        $this->grid->ExportSettings->IgnorePaging = true;
//        $this->grid->GetInstanceMasterTable()->ExportToCSV();
//    }
//
//    public function exportDoc($file_name) {
//        ob_end_clean();
//        $this->ExportSettings->FileName = $this->grid_name;
//        $this->grid->ExportSettings->IgnorePaging = true;
//        $this->grid->GetInstanceMasterTable()->ExportToWord();
//    }
//
//}

?>
