<?php
$path_doc_root = $_SERVER["DOCUMENT_ROOT"];
require_once ($path_doc_root . "/config.php");
require_once($path_doc_root . "/include/KoolPHPSuite/KoolAjax/koolajax.php");
$koolajax->scriptFolder = "./../include/KoolPHPSuite/KoolAjax";
require_once($path_doc_root . "/include/KoolPHPSuite/KoolGrid/koolgrid.php");
require_once($path_doc_root . "/include/KoolPHPSuite/KoolCalendar/koolcalendar.php");
include_once("callbacks.php");

$db_con = mysql_connect($DB_HOST, $DB_USER, $DB_PASS);
mysql_select_db($DB_NAME, $db_con);


$ds_client_contact = new MySQLDataSource($db_con);
$ds_client_contact->SelectCommand = "SELECT tpl_client.NAME AS 'Client Name', tpl_shadow_supplier.CONTACT_NAME AS 'Contact Name', tpl_shadow_supplier.CONTACT_POSITION AS 'Contact Position', tpl_shadow_supplier.PHYSICAL_ADDRESS_STATE AS Region, "
        . "tpl_client.TELEPHONE_NO as 'Contact Number', tpl_shadow_root.STATE as 'State', 'Year', tpl_shadow_directory_period_offering.NAME AS 'Offer', CONCAT(\"$\",CAST(CAST(tpl_shadow_directory_period_offering.COST_EXCL_GST AS DECIMAL(9,2)) AS CHAR)) AS 'Price', "
        . "tpl_client.REC_ID as CLIENT_REC_ID, tpl_client.USERNAME, tpl_client.PASSWORD, tpl_shadow_root.REC_ID as SR_REC_ID  "
        . "FROM " . $DB_NAME . ".tpl_client "
        . "INNER JOIN " . $DB_NAME . ".tpl_shadow_root ON tpl_client.REC_ID = tpl_shadow_root.CLIENT_REC_ID "
        . "INNER JOIN " . $DB_NAME . ".tpl_shadow_supplier ON (tpl_shadow_root.rec_id = tpl_shadow_supplier.shadow_rec_id) "
        . "INNER JOIN " . $DB_NAME . ".tpl_shadow_directory_period_offering ON (tpl_shadow_directory_period_offering.SHADOW_ROOT_REC_ID = tpl_shadow_root.REC_ID) "
        //. "WHERE tpl_shadow_root.DIRECTORY_REC_ID = " . $_GET['dir'] . " and tpl_shadow_root.DIRECTORY_YEAR = \"" . $_GET['yr'] . "\" and  tpl_client.IS_DELETED=0 "
        . "WHERE tpl_shadow_root.DIRECTORY_PERIOD_REC_ID = " . $_GET['yr'] . " and  tpl_client.IS_DELETED=0 "
        . "ORDER BY tpl_client.NAME ASC";


$ds_client_contact_details = new MySQLDataSource($db_con);
$ds_client_contact_details->SelectCommand = "SELECT  tpl_client.REC_ID as REC_ID, tpl_client.FIRST_NAME as 'First Name', tpl_client.LAST_NAME as 'Last Name', tpl_client.USERNAME as 'Username', tpl_client.PASSWORD as 'Password', "
        . "tpl_client.EMAIL_ADDRESS as 'Email', tpl_client.REC_DATETIME as 'Last Login' "
        . " FROM " . $DB_NAME . ".tpl_client";
//. " LEFT JOIN " . $DB_NAME . ".tpl_shadow_root"
//. " ON tpl_client.REC_ID  = tpl_shadow_root.CLIENT_REC_ID"
//. " WHERE tpl_client.IS_DELETED=0 and tpl_shadow_root.DIRECTORY_REC_ID =" . $_GET['dir'];
//    $ds->SelectCommand = $ds_client_contact;
//    $ds->UpdateCommand = "UPDATE " . $DB_NAME . ".tpl_client SET NAME = '@NAME',FIRST_NAME = '@FIRST_NAME',LAST_NAME = '@LAST_NAME',USERNAME = '@USERNAME',PASSWORD = '@PASSWORD',EMAIL_ADDRESS = '@EMAIL_ADDRESS' where REC_ID=@REC_ID";
//    $ds->DeleteCommand = "UPDATE " . $DB_NAME . ".tpl_client SET IS_DELETED=1 where REC_ID=@REC_ID";

$grid = new KoolGrid("grid");
$grid->scriptFolder = "./../include/KoolPHPSuite/KoolGrid";
$grid->styleFolder = "default";
$grid->Width = "1024px";
$grid->AllowEditing = true;
$grid->AllowHovering = true;
$grid->AllowSelecting = true;
$grid->RowAlternative = true;
$grid->AllowDeleting = true;
$grid->AllowFiltering = true;
$grid->AjaxEnabled = true;
$grid->AjaxLoadingImage = "./../include/KoolPHPSuite/KoolAjax/loading/5.gif";
$grid->ColumnWrap = false;
$grid->FilterOptions = array("Start_With", "Equal", "Contain", "End_With");
$grid->PageSize = 25;

$client_contact_details = new GridTableView();
$client_contact_details->Width = "100%";
$client_contact_details->DataSource = $ds_client_contact_details;
$client_contact_details->AddRelationField("REC_ID", "CLIENT_REC_ID");
$client_contact_details->AutoGenerateColumns = true;
$client_contact_details->DisableAutoGenerateDataFields = "tpl_client.REC_ID";
$client_contact_details->AllowFiltering = false;
//$client_contact_details->ShowHeader = false;


$grid->MasterTable->DataSource = $ds_client_contact;
$grid->MasterTable->EditSettings->Mode = "Inline";
$grid->MasterTable->AddDetailTable($client_contact_details);
$grid->MasterTable->AutoGenerateExpandColumn = true;
$grid->MasterTable->AutoGenerateColumns = true;
$grid->MasterTable->DisableAutoGenerateDataFields = 'tpl_client.USERNAME,tpl_client.PASSWORD, CLIENT_REC_ID,  tpl_client.REC_DATETIME, tpl_shadow_root.REC_ID, SR_REC_ID';
$grid->MasterTable->Pager = new GridPrevNextAndNumericPager();
//$grid->MasterTable->AutoGenerateEditColumn = true;
$grid->MasterTable->EditSettings->Mode = "Form";
//Step 4: Process Grid
$grid->Process();
//$grid->ClientSettings->ClientEvents["OnRowMouseOver"] = "Handle_OnRowMouseOver";
$grid->ClientSettings->ClientEvents["OnRowSelect"] = "Handle_OnRowSelect";
$grid->ClientSettings->ClientEvents["OnRowClick"] = "Handle_OnRowClick";
$grid->ClientSettings->ClientEvents["OnRowDoubleClick"] = "Handle_OnRowDoubleClick";
if ($koolajax->isCallback)
    sleep(1);

$result = mysql_query("SELECT NAME from " . $DB_NAME . ".tpl_directory WHERE REC_ID = " . $_GET['dir']);
while ($row = mysql_fetch_array($result)) {
    $dirName = $row['NAME'];
    $diryear = $_GET['yr'];
}
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"> 
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="chrome=1"/>
        <script type="text/javascript" src="scripts/jquery-min.js"></script>
        <script type="text/javascript" src="scripts/koolgrid-click-events.js"></script>
        <?php echo $koolajax->Render(); ?>
    </head>
    <body>

        <div style='font-family: Arial; font-size: 12pt; font-weight: bold;'><?php echo $dirName; ?>&nbsp;&nbsp;&nbsp;&nbsp<?php echo $diryear; ?></div>
        <div id="rowResult"></div>
        <form id="theform" method="post">
            <?php echo $grid->Render(); ?>
            <input type="hidden" id="nam"/>
            <input type="hidden" id="client_rec_id"/>
            <input type="hidden" id="sr_rec_id"/>
            <input type="hidden" id="usr"/>
            <input type="hidden" id="pwd"/>   
        </form>
    </body>
</html>





