<?php
if (!isset($_SESSION)) {
    session_start();
}
if (!isset($_SESSION["uid"])) {
    include("login.php");
    return;
}
?>

<?php
$path_doc_root = $_SERVER["DOCUMENT_ROOT"];
require_once ($path_doc_root . "/config.php");
require_once($path_doc_root . "/include/KoolPHPSuite/KoolAjax/koolajax.php");
$koolajax->scriptFolder = "./../include/KoolPHPSuite/KoolAjax";
require_once($path_doc_root . "/include/KoolPHPSuite/KoolGrid/koolgrid.php");

$grid = new KoolGrid("grid");
$grid->scriptFolder = "./../include/KoolPHPSuite/KoolGrid";
$grid->styleFolder = "default";
$grid->Width = "1000px";
$grid->RowAlternative = true;
$grid->AjaxEnabled = true;
$grid->AjaxLoadingImage = $path_doc_root . "/include/KoolPHPSuite/KoolAjax/loading/5.gif";

$db_con = mysql_connect($DB_HOST, $DB_USER, $DB_PASS);
mysql_select_db($DB_NAME, $db_con);

$ds_shadow_dir_offering = new MySQLDataSource($db_con); //selects the directory offering for the client
$ds_shadow_dir_offering->SelectCommand = "SELECT REC_ID , SHADOW_REC_ID , NAME , CONCAT(\"$\",CAST(CAST(tpl_shadow_directory_offering.COST_EXCL_GST AS DECIMAL(9,2)) AS CHAR)) AS 'Price', REC_DATETIME as Date "
        . "FROM tpl_shadow_directory_offering";

$table_tpl_dir_offering = new GridTableView();
$table_tpl_dir_offering->Width = "100%";
$table_tpl_dir_offering->DataSource = $ds_shadow_dir_offering;
$table_tpl_dir_offering->AddRelationField("REC_ID","SHADOW_DIRECTORY_OFFERING_REC_ID");
$table_tpl_dir_offering->AutoGenerateColumns = true; //Auto Generate all column from tables
$table_tpl_dir_offering->DisableAutoGenerateDataFields = "REC_ID, SHADOW_REC_ID"; //Disable generate column for orderNumber data fields.

$ds_shadow_root = new MySQLDataSource($db_con); //This $db_con link has been created inside KoolPHPSuite/Resources/runexample.php
$ds_shadow_root->SelectCommand = "SELECT  tpl_shadow_root.CLIENT_REC_ID as CLIENT_REC_ID, tpl_shadow_root.SHADOW_DIRECTORY_OFFERING_REC_ID, tpl_shadow_root.REC_ID as REC_ID,tpl_directory.NAME as Name,tpl_shadow_root.DIRECTORY_YEAR as Year "
        . " FROM " . $DB_NAME . ".tpl_shadow_root"
        . " LEFT JOIN " . $DB_NAME . ".tpl_directory"
        . " ON tpl_shadow_root.DIRECTORY_REC_ID  = tpl_directory.REC_ID";

$table_tpl_shadow = new GridTableView();
$table_tpl_shadow->Width = "100%";
$table_tpl_shadow->DataSource = $ds_shadow_root;
$table_tpl_shadow->AddRelationField("CLIENT_REC_ID", "CLIENT_REC_ID");
$table_tpl_shadow->AutoGenerateExpandColumn = true;
$table_tpl_shadow->AutoGenerateColumns = true;
$table_tpl_shadow->DisableAutoGenerateDataFields = "CLIENT_REC_ID, SHADOW_DIRECTORY_OFFERING_REC_ID";
$table_tpl_shadow->AddDetailTable($table_tpl_dir_offering);

$ds_client = new MySQLDataSource($db_con); //This $db_con link has been created inside KoolPHPSuite/Resources/runexample.php
$ds_client->SelectCommand = "SELECT  tpl_client.REC_ID as CLIENT_REC_ID, tpl_client.NAME as 'Client Name', tpl_client.USERNAME as 'User Name',tpl_client.FIRST_NAME as 'First Name',tpl_client.LAST_NAME as 'Last Name',tpl_client.EMAIL_ADDRESS as 'E-mail',tpl_client.REC_DATETIME as Date"
        . " FROM " . $DB_NAME . ".tpl_client"
        . " LEFT JOIN " . $DB_NAME . ".tpl_shadow_root"
        . " ON tpl_client.REC_ID  = tpl_shadow_root.CLIENT_REC_ID order by tpl_client.NAME";

$grid->MasterTable->DataSource = $ds_client;
$grid->MasterTable->AutoGenerateExpandColumn = true;
$grid->MasterTable->AutoGenerateColumns = true;
$grid->MasterTable->AddDetailTable($table_tpl_shadow);
$grid->MasterTable->DisableAutoGenerateDataFields = 'CLIENT_REC_ID';
$grid->MasterTable->Pager = new GridPrevNextAndNumericPager();
$grid->Process();


?>

<form id="form1" method="post">
    <?php echo $koolajax->Render(); ?>
    <?php echo $grid->Render(); ?>
</form>